/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://uceitidt2jeq5jvhduob2cfd4u.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-rdb6cpaxprcevo7b6aqfwmarom",
    "aws_cognito_identity_pool_id": "us-east-1:5ff6b5ff-adac-4d32-bcd8-6568c5292e10",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_F5olLBXPf",
    "aws_user_pools_web_client_id": "4jhikdpct4b982rnr0lqu5qv83",
    "oauth": {}
};


export default awsmobile;
